### ISSUE TITLE
Crash when passing an undefined source

### ISSUE THREAD

**Issue by fvsch** [ScreamZ/react-native-true-sight#1]
`<VideoPlayer source={undefined} />` crashes the app on iOS. This might be because the RN Video component is not forgiving of such errors. Should this component intercept the error?

Two options: throwing an explicit error or rendering an empty container (no `<Video/>`).

**Comment by ScreamZ** [comment]
Nice catch, I would rather render an empty container but marking the props as required should trigger the warning, isn't ?

Thanks

**Comment by fvsch** [comment]
After looking more it seems the crashing behavior might be unrelated.

**Comment by fvsch** [comment]
Aaaand correction again, passing an `undefined` source does crash the app. ^^

**Comment by ScreamZ** [comment]
@fvsch 2 years later but released a new 2.0.0 version that could help to solve this issue, also with full TS support.
Video is now external
