### ISSUE TITLE
Loader always showing

### ISSUE THREAD

**Issue by fabio-C** [ScreamZ/react-native-true-sight#10]
The library works, but the red loader is alway visible.
I am using local video files (in SD), so why the loader appears?

Thanks

-----------------------------
Android 9 
React Native 0.62.2
react-native-true-sight: ^1.0.2

**Comment by ScreamZ** [comment]
isLoading: currentTime >= meta.playableDuration

If the video is not buffered enough you get the loader.
I'll send a 2.0.0 update, let's try it

**Comment by garciabruno** [comment]
This is caused due to a bug in react-native-video.
When playing local files the progress status sets "playableDuration" to 0, causing the bug.

If you have a variable to distinguish between files from local disk or from the internet (in my case `isVideoFromLocal`) then you can use the following trick to fix the issue:

```javascript
<VideoPlayer
  autoStart={true}
  mainControl={args => <DefaultMainControl restartButton={true} {...args} />}
  bottomControl={args => <DefaultBottomControlsBar {...args} />}
>
  {args => (
    <Video
      ref={args.playerRef}
      source={{ uri: videoUrl }}
      paused={args.videoPaused}
      onLoad={args.onLoad}
      onProgress={(progressStatus) => {

        /*
         If the file is from local disk then set playableDuration to seekableDuration
         to fix infinite loading indicator on video
        */

        if (isVideoFromLocal) {
          progressStatus.playableDuration = progressStatus.seekableDuration;
        }

        args.onProgress(progressStatus)
      }
      }
      onEnd={args.onEnd}
      style={styles.BackgroundVideo}
      resizeMode={"contain"}
    />
    )}
</VideoPlayer>
```

Hope it helps. Cheers.
