### ISSUE TITLE
Hook when controls are shown/hidden

### ISSUE THREAD

**Issue by garciabruno** [ScreamZ/react-native-true-sight#12]
Hello, I would like to perform an action when the screen is tapped, currently the only thing it does is hide/show main control and bottom controls. 

Currently there's no way to hook into the onPressed event on VideoPlayer component. This could be an extra optional prop on VideoPlayer component that gets called on the same Callback

https://github.com/ScreamZ/react-native-true-sight/blob/master/src/modules/video-player/components/VideoPlayer.tsx#L109

**Comment by ScreamZ** [comment]
@garciabruno Could you achieve it by wrapping the full component with a onClick handler ?
