### ISSUE TITLE
passthrough props?

### ISSUE THREAD

**Issue by ppatel890** [ScreamZ/react-native-true-sight#3]
This component does a great job wrapping the `react-native-video` component, and adding visually appealing UI components. Any thoughts on enabling an ability to pass through props to the `react-native-video` component, so we can leverage some of the other props that are available on the video player?

**Comment by ScreamZ** [comment]
Yep, i'll add support for destructuring operator support. :)

**Comment by ScreamZ** [comment]
@ppatel890 2 years later but released a new 2.0.0 version that could help to solve this issue, also with full TS support.
Video is now external
