### ISSUE TITLE
On debug mode : Can't see the all action bar ( Play, Restart, and navigators)

### ISSUE THREAD

**Issue by JerryChild** [ScreamZ/react-native-true-sight#4]

**Comment by ScreamZ** [comment]
Can you be more explicit ?

Show me you implementation…

**Comment by JerryChild** [comment]
I change the title. 
It's only happen on debug mode.
On normal mode, all work fine

**Comment by ScreamZ** [comment]
There is no code about devmode are you sure this is not related to your implementation ? You can see the player but no the controls ?
