### ISSUE TITLE
Big fingers slider touchable too thin

### ISSUE THREAD

**Issue by jonathangreco** [ScreamZ/react-native-true-sight#5]
Hi,

First, I wanna say that is the best player plugin I've tested yet for Android, so thank you for your work.

I've encountered an issue I described it below.

## Context
Play a video in Landscape mode.
I try to be rude with the controls. Move the slider left right etc..

Tested on samsung 'SM-T580 - 7.0' (android 7)

## Issue
If we are not accurate, the slider won't move, and the controls fade instead, it's too hard to be accurate.

The slider should have a bigger touchable zone so we can move it more easily.

What do you think ?

**Comment by ScreamZ** [comment]
Thanks :)

I'll take this in account for a further release. I'll use material guidelines for click area.

Release

**Comment by jonathangreco** [comment]
@ScreamZ Thanks for your feedback.

Can you tell me when you will be able to release this ? Please

**Comment by ScreamZ** [comment]
I'll take a look in the week, I just need to mount another stack up, but I'm a bit busy.

You can bypass this by copying the current bar and use your own as described [here](https://github.com/ScreamZ/react-native-true-sight/blob/master/doc/custom-controls-bar.md), waiting this.

**Comment by ScreamZ** [comment]
@jonathangreco 2 years later but released a new 2.0.0 version that could help to solve this issue, also with full TS support.
You can make your own control if needed extending mine.
