### ISSUE TITLE
Video don't play if duration is too low (under 10 seconds ?)

### ISSUE THREAD

**Issue by jonathangreco** [ScreamZ/react-native-true-sight#6]
Hi,

I've an issue with th player if the video is under ten seconds. The video don't start even if player button is played.

Do you experienced the same issue ?

**Comment by ScreamZ** [comment]
Hello,

Nop didn't encoutered because I didn't used video of such duration. This library rely on `react-native-video` did you get the latest ?

**Comment by jonathangreco** [comment]
In fact  I can give you extra informations about this :

## Context
A video in internal storage area can be played if the duration is > 10 seconds. (/data/0/etc...)
A video in gallery can play regardless of its duration. After I recorded it with react-native camera and call the SaveToCameraRoll method.

A video with short duration wont play, sometimes the first frame will be loaded then buttons are "disabled" or doing nothing and sometimes it's just show a black screen.

It's not relative to your plugin, in fact, but I don't know how to fix it.

You can find my issue here https://github.com/react-native-community/react-native-video/issues/1311

**Comment by jonathangreco** [comment]
Issue has been resolved, it was a react-native-video issue.
