### ISSUE TITLE
Failed prop type: invalid prop `source` supplied

### ISSUE THREAD

**Issue by FrenchSam** [ScreamZ/react-native-true-sight#9]
Looks like the propType for `source` needs to be updated; it's still expecting `PropTypes.oneOfType([PropTypes.string, PropTypes.number])`.

**Comment by ScreamZ** [comment]
I'll totally revamp this library with hooks and less encapsulation to allow accessing the Video component itself in an easier way. I've written that 2/3 years ago and I had way less experience than now for making libs 😅

Waiting for that, I switched the props to any :)

**Comment by ScreamZ** [comment]
@FrenchSam Released a new 2.0.0 version that could help to solve this issue, also with full TS support
